import 'package:flutter/material.dart' show ColorScheme, Brightness, Color;

import 'app_colors.dart';

const ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.black,
  onPrimary: AppColors.white,
  primaryContainer: AppColors.lE5F0FB,
  onPrimaryContainer: Color(0xff141311),
  secondary: AppColors.black,
  onSecondary: AppColors.l2B4B5F,
  secondaryContainer: Color(0xffffffff),
  onSecondaryContainer: Color(0xff141414),
  tertiary: AppColors.cB9DDE8,
  onTertiary: Color(0xff000000),
  tertiaryContainer: Color(0xffEDEDED),
  onTertiaryContainer: Color(0xff141413),
  error: Color(0xffb00020),
  onError: Color(0xffffffff),
  errorContainer: Color(0xfffcd8df),
  onErrorContainer: Color(0xff141213),
  background: Color.fromARGB(255, 253, 247, 243),
  onBackground: Color(0xff0a0909),
  surface: Color(0xfffffbf9),
  onSurface: AppColors.black,
  surfaceVariant: Color(0xffeee8e3),
  onSurfaceVariant: Color(0xff121211),
  outline: Color(0xff837676),
  outlineVariant: Color(0xffccc6c6),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xff171411),
  onInverseSurface: Color(0xfff5f5f5),
  inversePrimary: Color(0xfffff8c0),
  surfaceTint: AppColors.transparent,
);

const ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.white,
  onPrimary: AppColors.d2C5A72,
  primaryContainer: AppColors.d284151,
  onPrimaryContainer: AppColors.dodgerBlue,
  secondary: Color(0xff5EB4F6),
  onSecondary:AppColors.dodgerBlue,
  secondaryContainer: AppColors.dodgerBlue,
  onSecondaryContainer: Color(0xfff3e6e2),
  tertiary: AppColors.dodgerBlue,
  onTertiary: Color(0xff131414),
  tertiaryContainer: Color(0xff6C7882),
  onTertiaryContainer: Color(0xffeaf7fb),
  error: Color(0xffcf6679),
  onError: Color(0xff140c0d),
  errorContainer: Color(0xffb1384e),
  onErrorContainer: Color(0xfffbe8ec),
  background: Color(0xff17212B),
  onBackground: AppColors.dodgerBlue,
  surface: Color(0xff181a1d),
  onSurface: Color(0xffeceded),
  surfaceVariant: Color(0xff3d4146),
  onSurfaceVariant: Color(0xffe0e1e1),
  outline: AppColors.dodgerBlue,
  outlineVariant: AppColors.dodgerBlue,
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xfffafcff),
  onInverseSurface: Color(0xff131314),
  inversePrimary: Color(0xff536577),
  surfaceTint: Color(0xffffffff),
);
